### ISSUE TITLE
Missing requires in module-info.java

### ISSUE THREAD

**Issue by armin-reichert** [io7m/jobj#4]
After cloning the repository I get a build error caused by a missing requires... in module-info.java. Adding
`requires com.io7m.junreachable.core;` fixed the error.

**Comment by io7m** [comment]
That's really strange that this hasn't come up until now. I didn't see the error you saw, but I did see a `maven-dependency-plugin` error:

```
[INFO] --- maven-dependency-plugin:3.6.1:analyze-only (analyze) @ com.io7m.jobj.core ---
[ERROR] Used undeclared dependencies found:
[ERROR]    com.io7m.junreachable:com.io7m.junreachable.core:jar:4.0.0:compile
[ERROR] Non-test scoped test only dependencies found:
[ERROR]    com.io7m.junreachable:com.io7m.junreachable.core:jar:4.0.0:compile
```

There was a missing test-scoped Maven dependency. I'm not certain why the various CI systems I use never caught this. It's now fixed on `develop`.
